//go:build ignore

package main

// Generates two files from plugin.cfg:
//
//	zplugin.go              — blank imports that pull each plugin into the binary
//	app/zdirectives_gen.go  — ordered directives slice used by cache_app.go
//
// Mirrors the approach used by github.com/coredns/coredns/directives_generate.go
// so that plugin.cfg is the single place to add or remove a plugin.
//
// Plugin execution order is derived from the vendored coredns zdirectives.go
// rather than the order in plugin.cfg. This means bumping the coredns dependency
// and re-running `make generate` automatically reflects any upstream ordering
// changes in the committed generated files, with no manual intervention.
//
// External plugins (not present in the vendored coredns plugin tree) are placed
// immediately after the last internal plugin that precedes them in plugin.cfg.
//
// Usage (from repo root):
//
//	make generate
//
// or directly (paths are relative to cmd/node-cache/):
//
//	cd cmd/node-cache && go run directives_generate.go

import (
	"bufio"
	"go/format"
	"log"
	"os"
	"strings"
)

const (
	githubOrg         = "github.com/coredns"
	pluginBase        = githubOrg + "/coredns/plugin/"                                          // import prefix for internal plugins
	pluginFSPath      = "../../vendor/github.com/coredns/coredns/plugin/"                       // local FS check
	vendorZdirectives = "../../vendor/github.com/coredns/coredns/core/dnsserver/zdirectives.go" // ordering source
	pluginFile        = "plugin.cfg"
	importsOutput     = "zplugin.go"
	directivesOut     = "app/zdirectives_gen.go"
	header            = "// generated by directives_generate.go; DO NOT EDIT\n\n"
)

func main() {
	cfgNames, imports := parsePluginCfg()
	ordered := orderByVendor(cfgNames, imports)
	genImports(importsOutput, imports)
	genDirectives(directivesOut, ordered)
}

// parsePluginCfg reads plugin.cfg and returns (names in file order, name→import path).
func parsePluginCfg() ([]string, map[string]string) {
	f, err := os.Open(pluginFile)
	if err != nil {
		log.Fatalf("Failed to open %s: %v", pluginFile, err)
	}
	defer f.Close()

	var names []string
	imports := make(map[string]string)

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, ":", 2)
		if len(parts) != 2 {
			log.Fatalf("Invalid plugin.cfg line (want name:path): %q", line)
		}
		name, path := parts[0], parts[1]

		if _, ok := imports[name]; ok {
			log.Fatalf("Duplicate plugin entry %q", name)
		}

		// If the path exists under the vendored coredns plugin tree it is an
		// internal plugin; prepend the full module path. Otherwise treat path
		// as a complete external import path (e.g. github.com/example/myplugin).
		importPath := pluginBase + path
		if _, err := os.Stat(pluginFSPath + path); err != nil {
			importPath = path
		}

		names = append(names, name)
		imports[name] = importPath
	}
	if err := scanner.Err(); err != nil {
		log.Fatalf("Error reading %s: %v", pluginFile, err)
	}
	return names, imports
}

// readVendorOrder returns directive names from the vendored zdirectives.go in
// their canonical coredns execution order.
func readVendorOrder() []string {
	f, err := os.Open(vendorZdirectives)
	if err != nil {
		log.Fatalf("Failed to open %s: %v", vendorZdirectives, err)
	}
	defer f.Close()

	var order []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, `"`) && strings.HasSuffix(line, `",`) {
			order = append(order, strings.Trim(line, `",`))
		}
	}
	return order
}

// orderByVendor returns the final directive list ordered by the vendored
// zdirectives.go. Internal plugins follow that canonical order; external
// plugins are inserted immediately after the last internal plugin that
// precedes them in plugin.cfg.
func orderByVendor(cfgNames []string, imports map[string]string) []string {
	vendorOrder := readVendorOrder()

	// Build a set of names that appear in the vendor ordering.
	vendorSet := make(map[string]bool, len(vendorOrder))
	for _, n := range vendorOrder {
		vendorSet[n] = true
	}

	// For each external plugin, anchor it to the last internal plugin before
	// it in plugin.cfg (empty string means before all internals).
	anchor := make(map[string]string) // external name → anchor internal name
	lastInternal := ""
	for _, name := range cfgNames {
		if vendorSet[name] {
			lastInternal = name
		} else {
			anchor[name] = lastInternal
		}
	}

	// Build a map from each anchor to the externals that follow it,
	// preserving their relative order from plugin.cfg.
	afterInternal := make(map[string][]string)
	for _, name := range cfgNames {
		if !vendorSet[name] {
			a := anchor[name]
			afterInternal[a] = append(afterInternal[a], name)
		}
	}

	// Which internal plugins are actually included?
	included := make(map[string]bool, len(cfgNames))
	for _, name := range cfgNames {
		if vendorSet[name] {
			included[name] = true
		}
	}

	// Walk the vendor order, emit included internals and inject any anchored
	// externals immediately after each one.
	var result []string
	result = append(result, afterInternal[""]...) // externals before first internal
	for _, name := range vendorOrder {
		if included[name] {
			result = append(result, name)
			result = append(result, afterInternal[name]...)
		}
	}
	return result
}

func genImports(file string, imports map[string]string) {
	out := header + "package main\n\nimport (\n// Blank imports ensure plugin code is pulled in from vendor when building\n// the node-cache image. Managed via cmd/node-cache/plugin.cfg.\n"
	for _, path := range imports {
		out += `_ "` + path + `"` + "\n"
	}
	out += ")\n"
	formatAndWrite(file, out)
}

func genDirectives(file string, names []string) {
	out := header + "package app\n\n"
	out += `// directives lists the CoreDNS plugins included in this build, in the order
// they must be executed. Order is derived from the vendored coredns zdirectives.go
// so that bumping the coredns dependency and re-running ` + "`make generate`" + ` keeps
// it in sync automatically. External plugins follow their anchor in plugin.cfg.
var directives = []string{
`
	for _, name := range names {
		out += `"` + name + `",` + "\n"
	}
	out += "}\n"
	formatAndWrite(file, out)
}

func formatAndWrite(file, src string) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		log.Fatalf("Failed to format %s: %v\nsource:\n%s", file, err, src)
	}
	if err := os.WriteFile(file, formatted, 0644); err != nil {
		log.Fatalf("Failed to write %s: %v", file, err)
	}
	log.Printf("wrote %s", file)
}
