// generated by directives_generate.go; DO NOT EDIT

package app

// directives lists the CoreDNS plugins included in this build, in the order
// they must be executed. Order is derived from the vendored coredns zdirectives.go
// so that bumping the coredns dependency and re-running `make generate` keeps
// it in sync automatically. External plugins follow their anchor in plugin.cfg.
var directives = []string{
	"timeouts",
	"reload",
	"bufsize",
	"bind",
	"debug",
	"trace",
	"health",
	"pprof",
	"prometheus",
	"errors",
	"log",
	"dns64",
	"loadbalance",
	"cache",
	"rewrite",
	"template",
	"hosts",
	"loop",
	"forward",
	"whoami",
}
